import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:secretnotes/models/note_codec.dart';
import 'package:secretnotes/services/crypto_service.dart';

/// Pins the Dart client against the committed cross-language protocol vectors
/// (test/fixtures/protocol_vectors.json, generated by
/// tool/generate_test_vectors.dart). The web client asserts against the *same*
/// file, so any accidental change to a KDF parameter, HKDF info string, blob
/// layout, or codec shape breaks this test loudly instead of silently locking
/// users out across implementations.
void main() {
  final vectors = jsonDecode(
    File('test/fixtures/protocol_vectors.json').readAsStringSync(),
  ) as Map<String, dynamic>;

  Uint8List b64(String s) => base64Decode(s);

  group('deterministic derivations match the fixture exactly', () {
    final d = vectors['derivation'] as Map<String, dynamic>;
    final params = (d['kdfParams'] as Map).cast<String, dynamic>();

    late Uint8List masterKey;

    setUpAll(() {
      masterKey = CryptoService.deriveMasterKey(
        d['password'] as String,
        b64(d['kdfSaltB64'] as String),
        memoryKib: params['m'] as int,
        iterations: params['t'] as int,
        lanes: params['p'] as int,
      );
    });

    test('Argon2id master key', () {
      expect(masterKey, equals(b64(d['masterKeyB64'] as String)));
    });

    test('HKDF wrap key', () {
      expect(
        CryptoService.wrapKey(masterKey),
        equals(b64(d['wrapKeyB64'] as String)),
      );
    });

    test('HKDF auth key', () {
      expect(
        CryptoService.authKey(masterKey),
        equals(b64(d['authKeyB64'] as String)),
      );
    });

    test('server auth-hash', () {
      final a = vectors['authHash'] as Map<String, dynamic>;
      expect(
        CryptoService.authHash(
          b64(a['serverAuthSaltB64'] as String),
          CryptoService.authKey(masterKey),
        ),
        equals(a['authHashB64'] as String),
      );
    });
  });

  test('padding buckets match the fixture', () {
    for (final c in (vectors['padding'] as List).cast<Map<String, dynamic>>()) {
      expect(
        CryptoService.paddedSize(c['plaintextLen'] as int),
        equals(c['paddedSize'] as int),
        reason: 'paddedSize(${c['plaintextLen']})',
      );
    }
  });

  test('wrapped DEK decrypts to the expected DEK', () {
    final w = vectors['wrappedDek'] as Map<String, dynamic>;
    // Recover the wrapKey from the derivation vector.
    final d = vectors['derivation'] as Map<String, dynamic>;
    final wrapKey = b64(d['wrapKeyB64'] as String);
    expect(
      CryptoService.unwrapDek(wrapKey, b64(w['wrappedDekB64'] as String)),
      equals(b64(w['dekB64'] as String)),
    );
  });

  test('raw GCM blob decrypts to the expected plaintext', () {
    final g = vectors['gcm'] as Map<String, dynamic>;
    expect(
      CryptoService.gcmDecrypt(
        b64(g['keyB64'] as String),
        b64(g['blobB64'] as String),
      ),
      equals(utf8.encode(g['plaintextUtf8'] as String)),
    );
  });

  test('note blob decrypts and decodes to the expected map', () {
    final n = vectors['note'] as Map<String, dynamic>;
    final dek = b64(n['dekB64'] as String);

    // The padded payload decrypts back to the exact codec bytes...
    final codecBytes = CryptoService.decryptPayload(
      dek,
      b64(n['blobB64'] as String),
    );
    expect(codecBytes, equals(b64(n['codecBytesB64'] as String)));

    // ...which decode to the note the fixture describes.
    final note = NoteCodec.decode(Uint8List.fromList(codecBytes));
    final map = (n['map'] as Map).cast<String, dynamic>();
    expect(note.id, map['id']);
    expect(note.title, map['title']);
    expect(note.contentJson, map['content']);
    expect(note.colorIndex, map['color']);
    expect(note.createdAt.millisecondsSinceEpoch, map['created']);
    expect(note.updatedAt.millisecondsSinceEpoch, map['updated']);
  });
}
