// Generates the authoritative cross-language test vectors for the SecretNotes
// wire protocol, driven by the *real* `CryptoService` so the fixtures can never
// silently disagree with the Dart client.
//
//   dart run tool/generate_test_vectors.dart
//
// Writes test/fixtures/protocol_vectors.json directly (not via stdout, which
// `dart run` pollutes with build-hook banners).
//
// The fixture is consumed by:
//   * test/protocol_vectors_test.dart  — pins the Dart side against drift;
//   * the web client's crypto test suite — proves byte-for-byte parity.
//
// Two flavours of vector live here:
//   * Deterministic derivations (Argon2id, HKDF, padding, auth-hash) carry
//     exact expected bytes — assert equality.
//   * AES-GCM blobs are produced with a random nonce, so they are recorded once
//     and asserted by *decrypting* back to the expected plaintext, never by
//     re-encrypting to the same bytes.
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:secretnotes/models/note.dart';
import 'package:secretnotes/models/note_codec.dart';
import 'package:secretnotes/services/crypto_service.dart';

String b64(List<int> bytes) => base64Encode(bytes);

void main() {
  // --- Fixed inputs (never randomize: the fixture must be reproducible) -----
  const password = 'correct horse battery staple';

  // 16-byte KDF salt, fixed. This is the `kdf_salt` an account would store.
  final kdfSalt = Uint8List.fromList(
    List<int>.generate(16, (i) => i), // 00 01 02 ... 0f
  );

  final params = {
    'm': CryptoService.kdfMemoryKib,
    't': CryptoService.kdfIterations,
    'p': CryptoService.kdfLanes,
  };

  final masterKey = CryptoService.deriveMasterKey(
    password,
    kdfSalt,
    memoryKib: params['m']!,
    iterations: params['t']!,
    lanes: params['p']!,
  );
  final wrapKey = CryptoService.wrapKey(masterKey);
  final authKey = CryptoService.authKey(masterKey);

  // A fixed 32-byte DEK so the wrapped-DEK vector is stable across regenerations
  // (only its GCM nonce changes run to run).
  final dek = Uint8List.fromList(
    List<int>.generate(32, (i) => (i * 7 + 3) & 0xff),
  );
  final wrappedDek = CryptoService.wrapDek(wrapKey, dek);

  // The server-side login verifier, for documentation/parity of the server.
  final serverAuthSalt = Uint8List.fromList(
    List<int>.generate(16, (i) => 0xa0 + i),
  );
  final authHash = CryptoService.authHash(serverAuthSalt, authKey);

  // --- A concrete note through the full codec+encrypt path ------------------
  final note = Note(
    id: '3f2a1c00-0000-4000-8000-000000000001',
    title: 'Grocery list',
    contentJson: '[{"insert":"milk\\neggs\\n"}]',
    colorIndex: 3,
    createdAt: DateTime.fromMillisecondsSinceEpoch(1700000000000),
    updatedAt: DateTime.fromMillisecondsSinceEpoch(1700000123000),
  );
  final noteBytes = NoteCodec.encode(note);
  final noteBlob = CryptoService.encryptPayload(dek, noteBytes);

  // A raw GCM vector on a short, arbitrary plaintext (no padding layer).
  final gcmPlain = Uint8List.fromList(utf8.encode('hello gcm'));
  final gcmBlob = CryptoService.gcmEncrypt(dek, gcmPlain);

  // Padding buckets for a spread of plaintext lengths.
  final paddingCases = [0, 1, 100, 251, 252, 253, 508, 1020, 4096]
      .map((n) => {'plaintextLen': n, 'paddedSize': CryptoService.paddedSize(n)})
      .toList();

  final vectors = {
    '_comment':
        'Authoritative SecretNotes protocol vectors. Generated by '
        'tool/generate_test_vectors.dart from the real CryptoService. '
        'Do not edit by hand — regenerate.',
    'constants': {
      'argon2': {
        'type': 'Argon2id',
        'version': 0x13,
        'memoryKiB': CryptoService.kdfMemoryKib,
        'iterations': CryptoService.kdfIterations,
        'lanes': CryptoService.kdfLanes,
        'keyLength': CryptoService.keyLength,
      },
      'hkdf': {
        'hash': 'SHA-256',
        'wrapInfo': 'secretnotes:wrap:v1',
        'authInfo': 'secretnotes:auth:v1',
      },
      'gcm': {'nonceLen': 12, 'tagBits': 128, 'layout': 'nonce||ciphertext||tag'},
      'padding': {'header': 'uint32-be plaintext length', 'minBucket': 256},
    },
    // Exact-match (deterministic) vectors.
    'derivation': {
      'password': password,
      'kdfSaltB64': b64(kdfSalt),
      'kdfParams': params,
      'masterKeyB64': b64(masterKey),
      'wrapKeyB64': b64(wrapKey),
      'authKeyB64': b64(authKey),
    },
    'authHash': {
      '_note':
          'Computed server-side as base64(sha256(authSalt || authKey)); the '
          'client never needs this, included for server parity.',
      'serverAuthSaltB64': b64(serverAuthSalt),
      'authHashB64': authHash,
    },
    'padding': paddingCases,
    // Decrypt-to-verify (GCM is randomized on encrypt) vectors.
    'wrappedDek': {
      '_verify': 'gcmDecrypt(wrapKey, wrappedDekB64) == dekB64',
      'dekB64': b64(dek),
      'wrappedDekB64': b64(wrappedDek),
    },
    'gcm': {
      '_verify': 'gcmDecrypt(dek, blobB64) == plaintext',
      'keyB64': b64(dek),
      'plaintextUtf8': 'hello gcm',
      'blobB64': b64(gcmBlob),
    },
    'note': {
      '_verify':
          'decryptPayload(dek, blobB64) == codecBytes; '
          'JSON.parse(utf8(codecBytes)) == map',
      'dekB64': b64(dek),
      'map': {
        'id': note.id,
        'title': note.title,
        'content': note.contentJson,
        'color': note.colorIndex,
        'created': note.createdAt.millisecondsSinceEpoch,
        'updated': note.updatedAt.millisecondsSinceEpoch,
      },
      'codecBytesB64': b64(noteBytes),
      'blobB64': b64(noteBlob),
    },
  };

  const encoder = JsonEncoder.withIndent('  ');
  final out = File('test/fixtures/protocol_vectors.json');
  out.writeAsStringSync('${encoder.convert(vectors)}\n');
  stderr.writeln('wrote ${out.path}');
}
